<?php
/**
 * Typography preview / specimen page.
 * Source of truth: src/styles/typography.scss
 */
$pageTitle = 'Typography — MedRad Clinics';
?>
<!DOCTYPE html>
<html lang="en">
<?php include __DIR__ . '/../shared/head/head.php'; ?>
<body>

  <style>
    /* Page-local layout for the specimen table */
    .type-table { width: 100%; border-collapse: collapse; margin-top: var(--space-32); }
    .type-table th,
    .type-table td {
      text-align: left;
      vertical-align: middle;
      padding: var(--space-32) var(--space-16);
      border-bottom: 1px solid var(--color-border);
    }
    .type-table thead th {
      font: 600 12px/1.25 'Inter', sans-serif;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: var(--color-accent);
      border-bottom: 2px solid var(--color-border);
    }
    .type-table td.spec {
      font: 400 13px/1.5 'Inter', sans-serif;
      color: var(--color-text-muted);
      white-space: nowrap;
    }
    .type-table td.selector {
      font: 500 13px/1.5 ui-monospace, 'SF Mono', Menlo, monospace;
      color: var(--color-text);
      white-space: nowrap;
    }
    .type-sample { color: var(--color-text); }
  </style>

  <main class="container" style="padding-top: var(--space-128); padding-bottom: var(--space-128);">

    <p class="eyebrow" style="color: var(--color-accent);">Design System</p>
    <h1>Typography</h1>
    <p class="lead">Type specimen for MedRad Clinics. Every style is generated by the
      <code>font()</code> mixin in <code>src/styles/typography.scss</code>.</p>

    <table class="type-table">
      <thead>
        <tr>
          <th>Selector</th>
          <th>Sample</th>
          <th>Font</th>
          <th>Size</th>
          <th>Weight</th>
          <th>Line-height</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="selector">h1, .h1</td>
          <td><span class="h1 type-sample">Heading One</span></td>
          <td class="spec">Playfair</td><td class="spec">44 / 76px</td><td class="spec">400</td><td class="spec">0.95</td>
        </tr>
        <tr>
          <td class="selector">h2, .h2</td>
          <td><span class="h2 type-sample">Heading Two</span></td>
          <td class="spec">Playfair</td><td class="spec">34 / 56px</td><td class="spec">400</td><td class="spec">1.08</td>
        </tr>
        <tr>
          <td class="selector">h3, .h3</td>
          <td><span class="h3 type-sample">Heading Three</span></td>
          <td class="spec">Playfair</td><td class="spec">28 / 40px</td><td class="spec">400</td><td class="spec">1.08</td>
        </tr>
        <tr>
          <td class="selector">h4, .h4</td>
          <td><span class="h4 type-sample">Heading Four</span></td>
          <td class="spec">Inter</td><td class="spec">22 / 28px</td><td class="spec">600</td><td class="spec">1.08</td>
        </tr>
        <tr>
          <td class="selector">h5, .h5</td>
          <td><span class="h5 type-sample">Heading Five</span></td>
          <td class="spec">Inter</td><td class="spec">20px</td><td class="spec">600</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">h6, .h6</td>
          <td><span class="h6 type-sample">Heading Six</span></td>
          <td class="spec">Inter</td><td class="spec">17px</td><td class="spec">600</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">p, .p1</td>
          <td><span class="p1 type-sample">Body paragraph — the default reading size.</span></td>
          <td class="spec">Inter</td><td class="spec">16px</td><td class="spec">400</td><td class="spec">1.65</td>
        </tr>
        <tr>
          <td class="selector">.lead</td>
          <td><span class="lead type-sample">Lead / standfirst paragraph.</span></td>
          <td class="spec">Inter</td><td class="spec">19 / 24px</td><td class="spec">400</td><td class="spec">1.5</td>
        </tr>
        <tr>
          <td class="selector">small, .p2</td>
          <td><span class="p2 type-sample">Small text — fine print, captions, meta.</span></td>
          <td class="spec">Inter</td><td class="spec">13px</td><td class="spec">400</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">.eyebrow</td>
          <td><span class="eyebrow type-sample">Eyebrow / Section label</span></td>
          <td class="spec">Inter</td><td class="spec">12px</td><td class="spec">600</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">blockquote, .blockquote</td>
          <td><span class="blockquote type-sample">&ldquo;Treatment, not just imaging.&rdquo;</span></td>
          <td class="spec">Playfair</td><td class="spec">28 / 40px</td><td class="spec">400</td><td class="spec">1.08</td>
        </tr>
        <tr>
          <td class="selector">nav, .nav-link</td>
          <td><span class="nav-link type-sample">Navigation link</span></td>
          <td class="spec">Inter</td><td class="spec">14px</td><td class="spec">500</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">button, .btn</td>
          <td><button class="btn btn--primary">Button</button></td>
          <td class="spec">Inter</td><td class="spec">14px</td><td class="spec">600</td><td class="spec">1.25</td>
        </tr>
        <tr>
          <td class="selector">b, strong</td>
          <td><span class="type-sample"><b>Bold emphasis</b></span></td>
          <td class="spec">&mdash;</td><td class="spec">&mdash;</td><td class="spec">600</td><td class="spec">&mdash;</td>
        </tr>
        <tr>
          <td class="selector">i, em</td>
          <td><span class="type-sample"><i>Italic emphasis</i></span></td>
          <td class="spec">&mdash;</td><td class="spec">&mdash;</td><td class="spec">&mdash;</td><td class="spec">&mdash;</td>
        </tr>
        <tr>
          <td class="selector">.font-display</td>
          <td><span class="font-display type-sample">Playfair Display family utility</span></td>
          <td class="spec">Playfair</td><td class="spec">inherited</td><td class="spec">inherited</td><td class="spec">inherited</td>
        </tr>
        <tr>
          <td class="selector">.font-body</td>
          <td><span class="font-body type-sample">Inter family utility</span></td>
          <td class="spec">Inter</td><td class="spec">inherited</td><td class="spec">inherited</td><td class="spec">inherited</td>
        </tr>
      </tbody>
    </table>

  </main>

</body>
</html>
