<?php
/**
 * Typography preview / specimen page.
 * Source of truth: src/shared/typography.scss
 */
$pageTitle = 'Typography — MedRad Clinics';
?>
<!DOCTYPE html>
<html lang="en">
<?php include __DIR__ . '/shared/head.php'; ?>
<body>

  <main class="container" style="padding-top: var(--space-2xl); padding-bottom: var(--space-2xl); max-width: 880px;">

    <p class="eyebrow" style="color: var(--color-accent);">Design System</p>
    <h1>Typography</h1>
    <p class="lead">Type specimen for MedRad Clinics. Every style below is generated by the
      <code>font()</code> mixin in <code>src/shared/typography.scss</code>.</p>

    <hr style="margin: var(--space-xl) 0; border: none; border-top: 1px solid var(--color-border);" />

    <!-- Headings -->
    <p class="eyebrow" style="color: var(--color-accent); margin-bottom: var(--space-md);">Headings</p>

    <h1>Heading 1 &mdash; Display</h1>
    <p class="p2">h1 / .h1 &middot; Playfair &middot; 44 / 76px &middot; weight 400</p>

    <h2>Heading 2</h2>
    <p class="p2">h2 / .h2 &middot; Playfair &middot; 34 / 56px &middot; weight 400</p>

    <h3>Heading 3</h3>
    <p class="p2">h3 / .h3 &middot; Playfair &middot; 28 / 40px &middot; weight 400</p>

    <h4>Heading 4</h4>
    <p class="p2">h4 / .h4 &middot; Inter &middot; 22 / 28px &middot; weight 600</p>

    <h5>Heading 5</h5>
    <p class="p2">h5 / .h5 &middot; Inter &middot; 20px &middot; weight 600</p>

    <h6>Heading 6</h6>
    <p class="p2">h6 / .h6 &middot; Inter &middot; 17px &middot; weight 600</p>

    <hr style="margin: var(--space-xl) 0; border: none; border-top: 1px solid var(--color-border);" />

    <!-- Body copy -->
    <p class="eyebrow" style="color: var(--color-accent); margin-bottom: var(--space-md);">Body copy</p>

    <p class="lead">Lead paragraph &mdash; the standfirst that opens a section. Minimally invasive,
      image-guided procedures for conditions once managed only with open surgery.</p>
    <p class="p2">.lead / .p-lead &middot; Inter &middot; 19 / 24px &middot; weight 400</p>

    <p>Body paragraph (p / .p1). Interventional radiology uses imaging guidance &mdash; ultrasound,
      fluoroscopy, CT &mdash; to treat conditions through a few millimetres of access rather than
      open surgery. This is the default reading size. It also carries <b>bold emphasis</b> and
      <i>italic emphasis</i> inline.</p>
    <p class="p2">p / .p1 &middot; Inter &middot; 16px &middot; weight 400</p>

    <p class="p2">Small text (.p2 / small / .caption) &mdash; fine print, captions, meta. Inter &middot; 13px &middot; weight 400</p>

    <hr style="margin: var(--space-xl) 0; border: none; border-top: 1px solid var(--color-border);" />

    <!-- Labels + quote + UI -->
    <p class="eyebrow" style="color: var(--color-accent); margin-bottom: var(--space-md);">Labels, quote &amp; UI</p>

    <p class="eyebrow" style="color: var(--color-accent);">Eyebrow / Kicker / Tag</p>
    <p class="p2">.eyebrow / .section__label &middot; Inter &middot; 12px &middot; weight 600 &middot; uppercase</p>

    <blockquote style="margin: var(--space-md) 0;">&ldquo;Treatment, not just imaging.&rdquo;</blockquote>
    <p class="p2">blockquote &middot; Playfair &middot; 28 / 40px &middot; weight 400</p>

    <p style="margin-top: var(--space-md);">
      <button class="btn btn--primary">Primary button</button>
      <a href="#" class="btn btn--ghost">Ghost button</a>
    </p>
    <p class="p2">button / .btn / .cta &middot; Inter &middot; 14px &middot; weight 600</p>

  </main>

</body>
</html>
